version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: health-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: health_db
      POSTGRES_USER: health_user
      POSTGRES_PASSWORD: health_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - health-net

volumes:
  postgres_data:

networks:
  health-net:
    driver: bridge
